shopping_list = ["eggs", "bacon", "cheese", "bread", "tomatoes"]

print(shopping_list)
shopping_list.reverse()
print(shopping_list)
shopping_list.sort()
print(shopping_list)
print(len(shopping_list))
shopping_list.pop()
print(shopping_list)
shopping_list.insert(2, "carrot")
print(shopping_list)
shopping_list.append("butter")
print(shopping_list)
del(shopping_list[1])
print(shopping_list)
