locations = ["New York", "Sydney", "Tokio", "Kioto", "Rio de Janeiro"]
print(locations)
print(sorted(locations))
print(sorted(locations, reverse=True))
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)
